### ISSUE TITLE
cannot create temp file for here-document: Read-only file system

### ISSUE THREAD

**Issue by krestenlaust** [Georift/install-jellyfin-tizen#22]
43650K .......... .......... ..                              100% 87.3M=3.8s/tizen-studio/tools/ide/bin/tizen.sh: line 12: cannot create temp file for here-document: Read-only file system
/tizen-studio/tools/ide/bin/tizen.sh: line 15: cannot create temp file for here-document: Read-only file system
java.io.FileNotFoundException: /home/developer/tizen-studio-data/cli/logs/cli.log (No such file or directory)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:133)
        at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
        at org.apache.log4j.FileAppender.<init>(FileAppender.java:110)
        at org.apache.log4j.FileAppender.<init>(FileAppender.java:121)
        at org.tizen.ncli.ide.shell.Main.<init>(Main.java:102)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:120)
java.io.FileNotFoundException: /home/developer/tizen-studio/tools/.tizen-cli-config (Read-only file system)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.tizen.ncli.core.config.NCLIConfigLoader.writeProperties2File(NCLIConfigLoader.java:228)
        at org.tizen.ncli.core.config.NCLIConfigLoader.loadConf(NCLIConfigLoader.java:132)
        at org.tizen.ncli.core.config.NCLIConfigLoader.loadLocalConf(NCLIConfigLoader.java:91)
        at org.tizen.ncli.ide.shell.Main.initializeConfig(Main.java:318)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:177)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:121)
Transferring the package...
Transferred the package: /home/developer/Jellyfin.wgt -> /home/owner/share/tmp/sdk_tools/tmp
Installing the package...
java.lang.NullPointerException
        at org.tizen.ncli.util.ConfigXMLUtil.getAppID(ConfigXMLUtil.java:39)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.getAppID(InstallCLICommand.java:423)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.getTVInstallCmd(InstallCLICommand.java:375)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.installPackage(InstallCLICommand.java:283)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.call(InstallCLICommand.java:170)
        at org.tizen.ncli.subcommands.target.InstallCLICommand.call(InstallCLICommand.java:63)
        at org.tizen.ncli.subcommands.AbstractSubCommand.runCommand(AbstractSubCommand.java:76)
        at org.tizen.ncli.ide.shell.InstallCLI.execute(InstallCLI.java:70)
        at org.tizen.ncli.ide.shell.AbstractCLI.execute(AbstractCLI.java:91)
        at org.tizen.ncli.ide.shell.Main.run(Main.java:188)
        at org.tizen.ncli.ide.shell.Main.main(Main.java:121)
--------------------
Platform log view
--------------------

Failed to install Tizen application.
Total time: 00:00:10.073
time="2024-04-27T19:17:40+02:00" level=error msg="Error waiting for container: container a97c9f6e0e08145e1f0528612d19397a111f2941e8ad881d70d60c87991809eb: driver \"overlay2\" failed to remove root filesystem: unlinkat /var/lib/docker/overlay2/6b2054270217e4da4cbd9e42eb58d87eb8a20cb854c792c045df252da2f5e869: read-only file system"
C:\Users\kress>

**Comment by krestenlaust** [comment]
Possibly an issue on my part with not having much space on my PC

**Comment by Georift** [comment]
In that case lets close this, 🙂 feel free to re-open if you need.
